Controllers/RecordsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tabemory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tabemory.Data;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Tabemory.ViewModels;
using System.Text;

namespace Tabemory.Controllers
{
    public class RecordsController : Controller
    {
        private readonly TabemoryDbContext _context;

        public RecordsController(TabemoryDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return _context.Record != null ?
                         View(await _context.Record.ToListAsync()) :
                         Problem("Entity set 'TabemoryDbContext.Recipe'  is null.");
        }


        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string[] items)
        {

            var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Record record = new Record()
            {
                Genre_catch = items[0],
                Genre_name = items[1],
                Name = items[2],
                Address = items[3],
                Station_name = items[4],
                Open = items[5],
                Close = items[6],
                Url = items[7],
                Photo = items[8],
                UserId = loginUserId
            };


            ModelState.Remove("Reviews");
            if (ModelState.IsValid)
            {
                _context.Add(record);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "新しいレストランを登録しました。";
                return RedirectToAction(nameof(Index));
            }

            return View(record);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Record == null)
            {
                return NotFound();
            }

            var record = await _context.Record.Include("Reviews")
                .FirstOrDefaultAsync(m => m.RecordId == id);
            if (record == null)
            {
                return NotFound();
            }

            var recordView = new Record()
            {
                RecordId = record.RecordId,
                Name = record.Name,
                Address = record.Address,
                Station_name = record.Station_name,
                Genre_catch = record.Genre_catch,
                Genre_name = record.Genre_name,
                Open = record.Open,
                Close = record.Close,
                Photo = record.Photo,
                UserId = record.UserId
             };

            var reviewList = new List<Review>();

            if (record.Reviews.Count > 0)
            {
                foreach (var item in record.Reviews)
                {
                    reviewList.Add(new Review
                    {
                        ReviewId = item.ReviewId,
                        VisitDate = item.VisitDate,
                        Rating = item.Rating,
                        Comment = item.Comment
                    });
                }
            }

            var recordreview = new RecordReview() {
                Record = recordView,
                ReviewList = reviewList,
                Review = new Review()
            };

            return View(recordreview);

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int? id, RecordReview model, string[] values)
        {

            var review = new Review()
            {
                VisitDate = DateTime.Parse(values[0]),
                Rating = int.Parse(values[1]),
                Comment = values[2],
                RecordId = int.Parse(values[3])
            };

            _context.Add(review);
            await _context.SaveChangesAsync();

            if (id == null || _context.Record == null)
            {
                return NotFound();
            }

            var record = await _context.Record.Include("Reviews")
                .FirstOrDefaultAsync(m => m.RecordId == id);
            if (record == null)
            {
                return NotFound();
            }

            var recordView = new Record()
            {
                RecordId = record.RecordId,
                Name = record.Name,
                Address = record.Address,
                Station_name = record.Station_name,
                Genre_catch = record.Genre_catch,
                Genre_name = record.Genre_name,
                Open = record.Open,
                Close = record.Close,
                Photo = record.Photo,
                UserId = record.UserId
            };

            var reviewList = new List<Review>();

            if (record.Reviews.Count > 0)
            {
                foreach (var item in record.Reviews)
                {
                    reviewList.Add(new Review
                    {
                        ReviewId = item.ReviewId,
                        VisitDate = item.VisitDate,
                        Rating = item.Rating,
                        Comment = item.Comment,
                        Image = item.Image,
                    });
                }
            }

            model.Record = recordView;
            model.ReviewList = reviewList;
            model.Review = review;

            return View(model);

        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int[] value)
        {
            if (_context.Record == null)
            {
                return Problem("Entity set 'TabemoryDbContext.Recipe'  is null.");
            }
            var record = await _context.Record.FindAsync(value[0]);
            if (record != null)
            {
                _context.Record.Remove(record);
                TempData["AlertMessage"] = "選択したレストランを削除しました。";
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Tabemory.Data;
using Tabemory.Models;

namespace Tabemory.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly TabemoryDbContext _context;

        public ReviewsController(TabemoryDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var tabemoryContext = _context.Review.Include(r => r.Record);
            return View(await tabemoryContext.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }

            var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userReviews = _context.Record.Where(a => a.UserId == loginUserId);

            ViewData["RecordId"] = new SelectList(userReviews, "RecordId", "Name", review.RecordId);
            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,VisitDate,Rating,Comment,RecordId")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            ModelState.Remove("Record");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "レビューを編集しました。";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecordId"] = new SelectList(_context.Record, "RecordId", "Name", review.RecordId);
            return View(review);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Review == null)
            {
                return Problem("Entity set 'TabemoryDbContext.Review'  is null.");
            }
            var review = await _context.Review.FindAsync(id);
            if (review != null)
            {
                _context.Review.Remove(review);
                TempData["AlertMessage"] = "レビューを削除しました。";
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return (_context.Review?.Any(e => e.ReviewId == id)).GetValueOrDefault();
        }
    }
}

Views/Reviews/Edit.cshtml
@model Tabemory.Models.Review;
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;

@{
    var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
<div class="contents-container">
    <h1 class="page-title">レビュー編集</h1>
<div class="detail-container">
    
    <div class="p-3">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ReviewId" />
                <div class="form-group p-1">
                    <label name="VisitDate" class="control-label">訪問日</label>
                    <input asp-for="VisitDate" class="form-control" />
                    <span asp-validation-for="VisitDate" class="text-danger"></span>
                </div>
                <div class="form-group p-1">
                    <label name="Rating" class="control-label">レーティング</label>
                    <input asp-for="Rating" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group p-1">
                    <label name="Comment" class="control-label">コメント</label>
                    <input asp-for="Comment" class="form-control" />
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <div class="form-group p-1">
                    <label name="RecordId" class="control-label">レストラン名</label>
                    <select asp-for="RecordId" class="form-control" asp-items="ViewBag.RecordId"></select>
                    <span asp-validation-for="RecordId" class="text-danger"></span>
                </div>
                <div class="form-group p-1">
                    <input type="submit" value="保存" class="btn btn-warning" />
                </div>
            </form>
    </div>
    <div class="text-center">
        <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

<style>
    html, body {
        background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0,0,0,0.3)), url(/images/book.jpg);
        background-size: cover;
        background-attachment: fixed;
        background-position: center center;
        background-repeat: no-repeat;
        height: 100%;
    }

</style>

Views/Reviews/Index.cshtml
@model IEnumerable<Tabemory.Models.Review>;
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;

@{
    ViewData["Title"] = "Index";
    var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
<div class="contents-container">
<h1 class="page-title">レビュー履歴</h1>

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success alert-dismissable fade show m-1" role="alert">
        @TempData["AlertMessage"]
        <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

        @foreach (var item in Model)
        {
        @if (item.Record.UserId == loginUserId) {

             string stars = new String('★', item.Rating);

            <div class="restaurant-card">
                <div class="d-flex justify-content-between">

                    <div>
                        <h4 class="fw-bold"><a asp-controller="Records" asp-action="Details" asp-route-id="@item.Record.RecordId" class="text-center">@Html.DisplayFor(modelItem => item.Record.Name)</a></h4>
                        @* <p class="fw-bold">@Html.DisplayFor(modelItem => item.Record.Name)</p> *@
                        <p>@Html.DisplayFor(modelItem => item.VisitDate) @stars </p>
                        <p>@Html.DisplayFor(modelItem => item.Comment)</p>
                    </div>

                    <div class="d-flex flex-column justify-content-between">
                    <a asp-action="Edit" asp-route-id="@item.ReviewId"><button class="btn btn-warning">編集</button></a>
                        <form asp-controller="Reviews" asp-action="Delete" onSubmit="return check()">
                            <input type="hidden" name="id" value="@item.ReviewId" />
                            <input type="submit" value="削除" class="btn btn-warning" />
                        </form>
                </div>
                </div>
            </div>
            }
        }

</div>

<style>
    html, body {
        background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0,0,0,0.3)), url(/images/coffeepc.jpg);
        background-size: cover;
        background-attachment: fixed;
        background-position: center center;
        background-repeat: no-repeat;
        height: 100%;
    }

</style>

<script>
    function check() {
        if (window.confirm('このレビューを削除しますか？')) {
            return true;
        } else {
            window.alert('キャンセルしました。')
            return false;
        }
    }
</script>